add my files to the project
Abouzaid-dev/flutter_pages pull request #19
Opened 2024-08-26 17:00 UTC by mohamedAboalhawa

Mohamed Aboalhawa-status Screens 3

2024-08-26 17:37 UTC, hassanelmoselhy commented
hassan-mohamed-onboardin10

2024-08-27 00:50 UTC, Abouzaid-dev requested changes
الشغل دا كدا غلط احنا قولنا منحطش ال main في صفحة المشروع نهائي آخرك تجرب علي الmain الموجودة عدل شغلك بعد اذنك @mohamedAboalhawa

2024-08-28 00:09 UTC, Abouzaid-dev commented on images/payment2.png
المفروض تحط الصور جوا فولدر بنفس اسم مشروعك

2024-08-28 00:13 UTC, Abouzaid-dev commented on lib/status_screens/status_screens3.dart
قولنا تبدأ الصفحة بتاعتك ب Scaffold يعني مينفعش جوا صفحة تحط void main ولا طبعاً MaterialApp لان دول موجودين بالفعل جوا صفحة ال main.dart لما تخلص افتح الmain.dart وضيف بعد الMaterialApp  ال home وحط اسم الصفحة بتاعتك ولما ترن والدنيا تما ابعتلي.

2024-08-28 00:15 UTC, Abouzaid-dev commented on pubspec.lock
اللعب هنا غلط عليك دلوقتي رجع كل حاجة زي ما كانت او اعمل git clone من الأول

2024-08-28 00:15 UTC, Abouzaid-dev commented on pubspec.yaml
ايه دا يا حبي؟؟؟؟

2024-08-28 00:16 UTC, Abouzaid-dev commented on test/widget_test.dart
ملكش دعوة بالفولدر دا او امسحه من عندك خالص

2024-08-28 00:20 UTC, Abouzaid-dev reviewed
اعمل git clone من الأول وشوف اللي انا كاتبهولك علي كل صفحة وطبقة بعد أذنك انا هقفل الركويست دا وبكرا قبل العصر الاقيك مسلم الجديد مفيهوش غلطة وحسابي معاك في السشن الجاي علشان هنفخك ♥☺

2024-08-28 00:20 UTC, closed without merging